
namespace: enqualifyapp

# Image
image:
  #firma ismi ile oluşturulan customer api repo ismi yazılır.
  repository: dockerhub.io/enqualify-capi-....
  #mail ile güncel tag iletilir.
  tag: "20240813.1"
  pullPolicy: IfNotPresent

# Replica
replicaCount: 1

# Service
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Image
imagePullSecrets:
  - name: dockerhubsecret

# Deployment
strategy:
  type: Recreate

# Container
containerPorts:
  http: 8080

# Volume
volumes:
  appsettingsjs:
    configMap: enqualify-capi
  videopvc:
    persistentVolumeClaim:
      claimName: enqualify-capi-claim

# Volume
volumeMounts:
  - name: appsettingsjs
    mountPath: /opt/app-root/app/appsettings.json
    subPath: appsettings.json
  - name: videopvc
    mountPath: /opt/app-root/app/files

# Uygulama
application:
  database:
    connections:
      default: "Server=;Database=;User ID=;Password=;Connection Timeout=30;Encrypt=False;TrustServerCertificate=false"
    integration:
      servicebase: ""
      integrationserviceurl: ""
      integrationapikey: ""
      integrationapiaudience: ""
  tokens:
    auth:
      jwt:
        key: ""
    request:
      sign:
        key: ""