
namespace: enqualifyapp

# Image
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

# Replica
replicaCount: 1

# Service
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress
ingressClassName: nginx
rules:
  host: enqualifycapi.example.com

# Deployment
strategy:
  type: Recreate

# Container
containerPorts:
  http: 8080

# Volume
volumes:
  appsettingsjs:
    configMap: enqualify-capi
  videopvc:
    persistentVolumeClaim:
      claimName: enqualify-capi-claim

# Uygulama
application:
  database:
    connections:
      default: "Server=;Database=;User ID=;Password=;Connection Timeout=30;Encrypt=False;TrustServerCertificate=false"
    integration:
      servicebase: ""
      integrationserviceurl: ""
      integrationapikey: ""
      integrationapiaudience: ""
  tokens:
    auth:
      jwt:
        key: ""
    request:
      sign:
        key: ""